CouscousPHP/Couscous

composer.json, couscous.yml, website/less/templates.less, website/templates.twig
Hey everyone, here's a new template!
This one is a fork of the Sphinx theme used by [Read The Docs](http://readthedocs.org/). That original theme is licensed with MIT so we are allowed to fork it! For example Guzzle is on Read The Docs: [guzzle.readthedocs.org](http://guzzle.readthedocs.org/en/latest/).
Here is the repository: https://github.com/CouscousPHP/Template-ReadTheDocs
I think having a new template along the new (future) 1.1 version will help spread the word ;)
Screenshot:
[![](https://raw.githubusercontent.com/CouscousPHP/Template-ReadTheDocs/master/screenshot.png)](https://github.com/CouscousPHP/Template-ReadTheDocs)
=> New template: Read The Docs

src/Application/Cli/PreviewCommand.php
HTTP built-in server is a different process and it can stop for many reasons.
This pull request creates a checking in order to let the user know if the server stopped.
=> Check if HTTP built-in server is running

src/Application/Cli/InitTemplateCommand.php, src/Application/config.php
Not sure how much detail was/is wanted with an initial template.  
It offers an optional second argument for specifying the directory to place the template in, defaulting to 'website'.
Perhaps it would be better to read that from the yaml configuration?
Also, no documentation added with this (contrary to contributing.md, sorry).  It seems fairly self-documenting, but let me know if you think docs would be appropriate and where to put them.
=> adds an init:template command (fix #40)

docs/configuration.md, docs/getting-started.md
Just some quick updates to the documentation regarding CNAMEs, the preview IP address and deploying to a branch other than `gh-pages`.
=> Documentation fixes for #94, #95 and #105

src/CommandRunner/Git.php, tests/UnitTest/CommandRunner/GitTest.php
See #115. Single quotes are tricky in Windows' built-in command processor, so this converts them to double quotes.
=> Fix compatibility issues with Windows

src/Module/Markdown/Step/ProcessMarkdownFileName.php, tests/UnitTest/Module/Markdown/Step/ProcessMarkdownFileNameTest.php
Well, as I asked in #121, I'm looking for a way to show the home page but not using the README.md file.
The idea is to specify in the `couscous.yml` file:
```yml
index: index.md
```
And so Couscous should use `index.md` instead of `README.md`.
I don't know if my implementation is right, sorry about that. Maybe someone should take a look.
BTW I loved the project name, here in Brazil we call "cuscuz". I think I'm hungry.
I hope this PR helps, thank you.
=> Added support to render other files as home page than README.md

couscous.yml, docs/configuration.md, src/Application/config.php, src/Module/Core/Step/AddCname.php, src/Module/Template/Model/CnameFile.php, tests/UnitTest/Module/Core/Step/AddCnameTest.php, website/CNAME
This fixes the problem with CNAME and remote templates which is mentioned in the docs/configuration. Setting a `cname` metadata in `couscous.yml` generates a CNAME file.
=> Add metadata to generate a CNAME file

docs/configuration.md, src/Application/Cli/DeployCommand.php
Setting the branch metadata you can choose which branch to deploy.
Useful for deploying to a organization page. Fixes #133
=> Add branch metadata to configuration

docs/getting-started.md, website/home.twig
=> Provide information about Github DDOS protection when using CURL to download Couscous.

src/Model/Project.php
Pretty self-explanatory. 
No tests as I think we should be trusting Finder to honour its contract as it's a 3rd party library.
=> Add support for following symlinks

tests/UnitTest/Module/Markdown/Step/RenderMarkdownTest.php
Add tests to cover what is described in #156. That way we can follow precisely what is supported and what's not when we switch the Markdown engine.
=> #156 Add Markdown tests

src/Application/Cli/PreviewCommand.php
Many terminal emulators support clicking on URIs and automatically opening them in a browser - adding the protocol to the server address allows this link detection to work correctly.
Tested in OS X Terminal.app and iTerm2.app, both of which now handle the link correctly (by cmd+doubleclicking and cmd+clicking respectively) where they did not before the change.
=> Add http:// prefix to preview URI

src/Application/Cli/PreviewCommand.php
When using the `preview` command, sometimes the server stops and we have
no clue about the problem. Adding the process error output will help
users understand what's happening.
=> Display error output when the server goes down

src/Application/Cli/PreviewCommand.php
When using Couscous through Composer with scripts for example, Couscous might
get killed once a given timeout is reached: the child server process might not
be killed properly in this case.
PHP lets us catch kill signals (using `pcntl_signal`). Using this function we can
make Couscous propagate the signal it receives to its child process: the
server will then be killed by Couscous before it dies and everything will be ok.
=> Propagate kill signal to the child server process

website/default.twig, website/less/sidebar.less
This PR makes the documentation and other text-based pages boxed instead of full-width. This is much cleaner and friendlier to read.
It's a small change, but it's something ;P
=> Makes default pages boxed instead of full-width

CONTRIBUTING.md, docs/configuration.md, src/Model/ExcludeList.php, src/Model/Project.php, tests/UnitTest/Model/ExcludeListTest.php
This allows users to have their git ignored files and directories automatically
ignored by Couscous. To enable this feature, they will have to add the special
`%gitignore%` entry to their exclude list.
Why do we use a special entry? To keep the actual behavior unchanged and avoid
unexpected generation errors.
The actual implementation is a bit naïve: it will take each entry line from the
`.gitignore` and add them to the exclude list of Couscous. So we might end up
adding files and directories. It's hard to test every `.gitignore` entry to see
if the are actual directories: paths might be relative or patterns, starting
from the repository's root directory or not.
Moreover, the implementation does not support complex pattern as git would.
=> Read excluded directories from the `.gitignore` file of the repository

docs/getting-started.md
I noticed that there wasn't anything on the website about the new `self-update` command, so here's an addition to point it out.
Feel free to move this somewhere else. There wasn't really an existing page that talked about Couscous _itself,_ but maybe there should be?
=> Add documentation for self-update command

docs/configuration.md
Two examples, one without quotes and one with (to illustrate the correct placement of the `=` in the string).
=> Add documentation for CLI metadata

docs/travis.md
Github URL for creating a personal access token has changed. This PR simply fixes the link.
=> Fixing path to Github "create a personal access token" page

src/Application/Cli/TravisAutoDeployCommand.php
Fix #202
The option is not deprecated for now, it seems it's a leftover of #190 (the option was initially deprecated but then that was reverted).
=> Remove deprecation notice

src/Application/Cli/PreviewCommand.php
Fixes #221 as it appears Symfony 4 no longer supports the ProcessBuilder library.  I refactored the code to generate the Process object in a way that is compatible with Symfony 4.  No functionality should be affected.
All tests pass and 'couscous preview' runs locally.
=> Updated ProcessBuilder reference to fix bug with Symfony 4 upgrade

composer.json
Bumping the Symfony version fixes #227 . Not really sure what the actual issue is, it could also be fixed by passing a string to the Symfony Process in the preview command:
```
private function startWebServer(InputInterface $input, OutputInterface $output, $targetDirectory)
{
$processArguments = [PHP_BINARY, '-S', $input->getArgument('address')];
$process = new Process($processArguments);
```
but that will be deprecated in the Process component anyway I think.
=> Bump Symfony

src/CommandRunner/CommandRunner.php
Couscous is not compatible with windows because of this exec command:
```php
exec($command . ' 2>&1', $output, $returnValue);
```
The `couscous deploy` command crashes under windows:
```
Generating C:\...\Couscous\bin to C:\...\Couscous\bin/.couscous/generated
[notice] No couscous.yml configuration file found, using default config
[notice] Fetching template from https://github.com/CouscousPHP/Template-Light.git
Deploying the website
Cloning https://github.com/CouscousPHP/Couscous.git in C:\Users\...\Temp\couDDAD.tmp
Checking out branch gh-pages
Copying generated website
Committing changes
Pushing gh-pages (GitHub may ask you to login)
In CommandRunner.php line 29:
fatal: HttpRequestException encountered.                           
Fehler beim Senden der Anforderung. …
```
=> Fix command issues with windows

.travis.yml, composer.json, docs/travis.md, src/Application/Cli/TravisAutoDeployCommand.php, tests/FunctionalTest/BaseFunctionalTest.php, tests/FunctionalTest/CommandRunner/CommandRunnerTest.php, tests/UnitTest/CommandRunner/GitTest.php, tests/UnitTest/GeneratorTest.php, tests/UnitTest/Model/ExcludeListTest.php, tests/UnitTest/Model/FileTest.php, tests/UnitTest/Model/MetadataTest.php, tests/UnitTest/Model/ProjectTest.php, tests/UnitTest/Module/Config/Step/OverrideBaseUrlForPreviewTest.php, tests/UnitTest/Module/Config/Step/OverrideConfigFromCLITest.php, tests/UnitTest/Module/Config/Step/SetDefaultConfigTest.php, tests/UnitTest/Module/Core/Step/AddCnameTest.php, tests/UnitTest/Module/Core/Step/AddFileNameToMetadataTest.php, tests/UnitTest/Module/Core/Step/ClearTargetDirectoryTest.php, tests/UnitTest/Module/Markdown/Step/ProcessMarkdownFileNameTest.php, tests/UnitTest/Module/Markdown/Step/RenderMarkdownTest.php, tests/UnitTest/Module/Markdown/Step/RewriteMarkdownLinksTest.php, tests/UnitTest/Module/Template/Step/AddPageListToTemplateVariablesTest.php, tests/UnitTest/Module/Template/Step/FetchRemoteTemplateTest.php, tests/UnitTest/Module/Template/Step/UseDefaultTemplateTest.php, tests/UnitTest/Module/Template/Step/ValidateTemplateDirectoryTest.php
This PR drops support for PHP 5.6 and 7.0.
Supporting these versions was too much effort in order to fix the build.
=> Upgrade to PHP 7.1 and fix tests

CONTRIBUTING.md, README.md, couscous.yml, docs/configuration.md, docs/faq.md, docs/getting-started.md, docs/templates.md, docs/travis.md, src/Application/Cli/SelfUpdateCommand.php, tests/UnitTest/Module/Core/Step/AddCnameTest.php, tests/UnitTest/Module/Markdown/Step/RenderMarkdownTest.php, website/default.twig, website/home-portfolio.twig, website/home.twig
=> [#242] use HTTPS

docs/configuration.md
If we take the code here:
https://github.com/CouscousPHP/Couscous/blob/c168d0b9c1449d60f2a31b2a30c7ab7e61e419be/src/Model/Project.php#L127-L129
We see the `.gitignore` file is always read.
This PR changes the documentation to mention it correctly.
=> [Doc] The .gitignore file is always read
