docs/faq.md, src/Module/Markdown/Step/ProcessMarkdownFileName.php, src/Module/Markdown/Step/RewriteMarkdownLinks.php, tests/UnitTest/Module/Markdown/Step/ProcessMarkdownFileNameTest.php, tests/UnitTest/Module/Markdown/Step/RewriteMarkdownLinksTest.php
=> Improve renaming and replacement of file names

src/Module/Markdown/Step/CreateHeadingIds.php, src/Module/Markdown/config.php, tests/FunctionalTest/Fixture/headings/expected/index.html, tests/FunctionalTest/Fixture/headings/expected/other.html, tests/FunctionalTest/Fixture/headings/source/OTHER.md, tests/FunctionalTest/Fixture/headings/source/README.md, tests/FunctionalTest/Fixture/headings/source/website/default.twig, tests/FunctionalTest/GenerationTest.php
=> Auto-generate HTML IDs for headers

.travis.yml
* Fixed indentation as well to 4 spaces
=> Added PHP7 to travis.

src/CommandRunner/Git.php, tests/UnitTest/CommandRunner/GitTest.php
See #106. Unfortunately, I don't have the tools at the moment to set up compilation, so I can't actually test this.
=> Fixes command compatibility issues with Windows

.gitignore, CONTRIBUTING.md, bin/compile, composer.json, src/Application/Cli/SelfUpdateCommand.php, src/Application/config.php
Fixes #102
@mnapoli for this to work we first need to push a new couscous.phar and couscous.version online, can I do it?
=> Add a self update command to update the phar file.

src/Application/Cli/PreviewCommand.php
When killing Couscous with CTRL+C (SIGINT - 2) user got an exception telling him
the server went down. This is expected an no exception should be raised in this
case.
Moreover, when the server exited correctly (after receiving SIGTERM - 15), an
error was displayed and an exception was raised. Again this behavior was wrong:
everything exited successfully and the errors were misleading. This is fixed.
Now, when Couscous receives either SIGINT or SIGTERM, it will try to kill the
server process. If everything exits properly, the user only gets an information
message an no exception is raised. If Couscous fails to stop the server it will
display an error message and throw an exception containing the server's error
output.
=> Fix signal handling to avoid unexpected exceptions

website/templates.twig
Hello,
I've added the new template for Couscous which I've prepared for my open source project. It would be great if you could accept it and put on templates section. Maybe someone will use it :)
I'm adding the modified HTML template preview page for this request:
=> Added new template to project

website/templates.twig
Adding the Elephantly couscous template to the list
=> Adding ElephantlyCouscous

composer.json, phpcs.xml, src/Application/Cli/PreviewCommand.php, src/Module/Markdown/Step/ProcessMarkdownFileName.php
Use [prettyci.com](https://prettyci.com/) to enforce the PSR-2 standard.
=> Enforce PSR-2 compliance with PrettyCI

website/home-portfolio.twig
=> Fix link to Foli example

website/templates.twig
The target page will be replaced
=> Update template link

website/templates.twig
Thx for this beautiful tool, I wish to contribute by make DraculaTheme https://draculatheme.com/.
=> New Template : DraculaTheme

src/CommandRunner/Git.php, src/Deployer.php, tests/UnitTest/CommandRunner/GitTest.php
=> Skip deploy if no files were changed

website/templates.twig
Moved the repo to dracula Organization
=> Update url Repo DraculaTheme

docs/getting-started.md
This will allow us to move this location in the future without breaking all user's CI jobs
=> Curl follow redirects

src/Module/Core/Step/ClearTargetDirectory.php, tests/UnitTest/Fixture/directory-with-dot-files/.github/foobar.txt, tests/UnitTest/Fixture/directory-with-dot-files/.gitkeep, tests/UnitTest/Fixture/directory-with-dot-files/index.html, tests/UnitTest/Module/Core/Step/AddCnameTest.php, tests/UnitTest/Module/Core/Step/AddFileNameToMetadataTest.php, tests/UnitTest/Module/Core/Step/ClearTargetDirectoryTest.php
This PR does not add any features or changes. It just adds a test to make sure we dont change this behavior in the future.
=> Adding tests to ensure dot files are never removed

.travis.yml, release.sh, src/Application/config.php, travis-prepare-release.sh
This will fix #243
I made the assumption that this project always will be deployed with Travis.
=> Support --version

docs/faq.md, src/Module/Template/Step/ProcessTwigLayouts.php
=> Support custom twig extensions

couscous.yml, docs/README.md, docs/githubaction.md
Hi, 
I just made an action for Github : https://github.com/BilelJegham/action-couscous 
I add to the doc the github workflow.
Do you want to owe the repo on Couscous org ?
=> Github Action

.travis.yml
To make sure there isn't any incompatibilities
=> Test against PHP 7.4
